package com.rankminer.featurevectoranalyzer.translator;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.10.25 at 05:56:51 PM EDT 
//

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="resource" maxOccurs="unbounded">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="features" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
*                 &lt;/sequence>
*                 &lt;attribute name="fileId" type="{http://www.w3.org/2001/XMLSchema}int" />
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "resource"
})
@XmlRootElement(name = "resources")
public class Resources {

 @XmlElement(required = true)
 protected List<Resources.Resource> resource;

 /**
  * Gets the value of the resource property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the resource property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getResource().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Resources.Resource }
  * 
  * 
  */
 public List<Resources.Resource> getResource() {
     if (resource == null) {
         resource = new ArrayList<Resources.Resource>();
     }
     return this.resource;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="features" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded"/>
  *       &lt;/sequence>
  *       &lt;attribute name="fileId" type="{http://www.w3.org/2001/XMLSchema}int" />
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "fileName",
     "features"
 })
 public static class Resource {

     @XmlElement(required = true)
     protected String fileName;
     @XmlElement(type = Double.class)
     protected List<Double> features;
     @XmlAttribute
     protected Integer fileId;

     /**
      * Gets the value of the fileName property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getFileName() {
         return fileName;
     }

     /**
      * Sets the value of the fileName property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setFileName(String value) {
         this.fileName = value;
     }

     /**
      * Gets the value of the features property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the features property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getFeatures().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link Double }
      * 
      * 
      */
     public List<Double> getFeatures() {
         if (features == null) {
             features = new ArrayList<Double>();
         }
         return this.features;
     }

     /**
      * Gets the value of the fileId property.
      * 
      * @return
      *     possible object is
      *     {@link Integer }
      *     
      */
     public Integer getFileId() {
         return fileId;
     }

     /**
      * Sets the value of the fileId property.
      * 
      * @param value
      *     allowed object is
      *     {@link Integer }
      *     
      */
     public void setFileId(Integer value) {
         this.fileId = value;
     }

 }

}
