package com.rankminer.featurevectoranalyzer;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

import com.rankminer.featurevectoranalyzer.translator.Resources;
import com.rankminer.featurevectoranalyzer.translator.Resources.Resource;

/**
 * Purpose of this class is to read the xml file generated by the console-connector application
 * and output the csv file.
 * @author achavan
 *
 */
public class FeatureVectorConverter {
	/**
	 * Reads the source xml file and converts it to an output format 
	 * in csv
	 * @param sourceFileName
	 * @param destinationFileName
	 */
	public void convertFeatureVectorXmlToCsv(String sourceFileName, String destinationFileName) {
		System.out.println("Reading feature vector file "+ sourceFileName);
		File file = new File(sourceFileName);
		JAXBContext jaxbContext;
		try {
			jaxbContext = JAXBContext.newInstance(Resources.class);
			Unmarshaller jaxbMarshaller = jaxbContext.createUnmarshaller();
			Resources resources = (Resources)jaxbMarshaller.unmarshal(file);
			createCsvFile(resources,destinationFileName);
			
		} catch (JAXBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	private void createCsvFile(Resources resources, String destinationFileName)  {
		BufferedWriter writer;
		try {
			writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(destinationFileName)));
			
			for(Resource resource : resources.getResource()) {
				StringBuilder builder = new StringBuilder();
				builder.append(resource.getFileName()).append(",");
				for(double d : resource.getFeatures()) {
					builder.append(d).append(",");
				}
				builder.deleteCharAt( builder.length() -1 );
				writer.write(builder.toString());
				writer.newLine();
			}
			writer.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}
}
